#!/bin/bash
SCALA_VERSION=2.7.6
PROJECT_DIR=/Users/tristan/dev/knockoff
CLASSPATH=$PROJECT_DIR/project/boot/scala-$SCALA_VERSION/lib/scala-library.jar
CLASSPATH=$CLASSPATH:$PROJECT_DIR/target/scala_$SCALA_VERSION/knockoff_2.7.6-0.5.0-SNAPSHOT.jar
java -cp $CLASSPATH knockoff.DefaultDiscounter "$@"