#!/bin/bash
SCALA_VERSION=2.8.0.Beta1
PROJECT_DIR=/Users/tristan/dev/knockoff
# # The local project's scala version is part of the target directory we'll search for
PROJECT_VERSION=`grep project.version $PROJECT_DIR/project/build.properties | sed -e s'/project.version=//'`
# # The local project's scala version is part of the target directory we'll search for
# SCALA_VERSION=`grep scala.version $PROJECT_DIR/project/build.properties | sed -e s'/scala.version=//'`

CLASSPATH=$PROJECT_DIR/project/boot/scala-$SCALA_VERSION/lib/scala-library.jar
CLASSPATH=$CLASSPATH:$PROJECT_DIR/target/scala_$SCALA_VERSION/knockoff_$SCALA_VERSION-$PROJECT_VERSION.jar
java -cp $CLASSPATH com.tristanhunt.knockoff2.MarkdownConsole "$@"