#!/bin/sh
#
# A stupid release script, until I figure out what I want to do with this later.

BUILD_NUMBER=6
VERSION_BASE=`grep project.version project/build.properties | sed -e 's/project.version=//'`
VERSION_NUMBER=`echo $VERSION_BASE | sed -e "s/SNAPSHOT/$BUILD_NUMBER/"`

echo Checking out $VERSION_NUMBER-build
git checkout -b $VERSION_NUMBER-build

echo Changing $VERSION_BASE to $VERSION_NUMBER in project/build.properties
for file in project/build.properties `find . -name '*.markdown'`
do
  cat $file | sed -e "s/$VERSION_BASE/$VERSION_NUMBER/g" > $file.tmp
  rm $file
  mv $file.tmp $file
done

echo Build preparation
sbt clean clean-lib update lit

echo Committing
git commit -m "$VERSION_NUMBER release" -a

echo Cross-compiling
sbt +package

SCALA_VERSION=`grep scala.version project/build.properties | sed -e s'/scala.version=//'`

echo Publishing
sbt +publish

git reset --hard HEAD 

git tag $VERSION_NUMBER

git push --tags

git checkout master

echo You should update target/doc now