#!/bin/sh

BUILD_NUMBER=1
VERSION_BASE=`grep project.version project/build.properties | sed -e 's/project.version=//'`
VERSION_NUMBER=`echo $VERSION_BASE | sed -e "s/SNAPSHOT/$BUILD_NUMBER/"`

echo Checking out $VERSION_NUMBER
git checkout -b $VERSION_NUMBER

echo Changing $VERSION_BASE to $VERSION_NUMBER in project/build.properties
cat project/build.properties | sed -e "s/$VERSION_BASE/$VERSION_NUMBER/" > project/build.properties.tmp
rm project/build.properties
mv project/build.properties.tmp project/build.properties

echo Committing
git commit -m "$VERSION_NUMBER release" -a

echo Build preparation
sbt clean clean-lib update literate

echo Cross-compiling
sbt +package

SCALA_VERSION=`grep scala.version project/build.properties | sed -e s'/scala.version=//'`

echo Preparing Documentation
sbt doc
cp -r target/scala_$SCALA_VERSION/doc/main target/doc

echo Publishing
sbt +publish

git push origin $VERSION_NUMBER

echo You should update target/doc now